<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<!--
Design by unknown
Modified by BalandinDS
Name       : Test
Description: Simply test theme.
-->
<?php

	$http_host = $_SERVER['HTTP_HOST'];
	$tmpl_base_dir = str_replace("\\", "/", explode($http_host, substr(dirname(__FILE__), strrpos(dirname(__FILE__), $http_host)))[1]);
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<title><?= $title; ?></title>
	<link rel="stylesheet" type="text/css" href="<?= $tmpl_base_dir; ?>/css/style.css" />
</head>
<body>
	<header>
        Hello, <?= $user_name; ?>
        <hr>
	  <h1>
          <?= $header; ?>
      </h1>
	</header>

	<section>
		<article>
			<?//= '';// $message; ?>
            <?php  
            	include $template_content;
            ?>

		</article>

		<aside>
		    <?php include $template_menu; ?>
	  	</aside>
	</section>

	<footer>
		&copy; <a href="" target="_blank" title="isGood.">Site</a> <?= date('Y'); ?>
	</footer>

</body>
</html>